PHP 8.1: fix the other test
In this particular test, a shortcut was taken in the mocking method call expectations.
While this worked fine for PHP < 8.1, on PHP 8.1 type checking is done more strictly, so the expectations have to be set more strictly as well.

This adjusts the expectations to match the expected method calls and output for various PHP versions _exactly_ and with this change, the test will also pass on PHP 8.1.

Fixes the following test failure as per https://github.com/Brain-WP/BrainMonkey/issues/103#issuecomment-927148428
```
Brain\Monkey\Tests\Unit\Name\ClosureParamStringFormTest::testFromReflectionToString7
TypeError: Mockery_3_ReflectionParameter::getType(): Return value must be of type ?ReflectionType, string returned

/home/runner/work/BrainMonkey/BrainMonkey/src/Name/ClosureParamStringForm.php:82
/home/runner/work/BrainMonkey/BrainMonkey/tests/cases/unit/Name/ClosureParamStringFormTest.php:100
```